Repository excitr/sound-cloud-helper, pull requests merged in 2024-09, with the labels that each got.

#1 separate
  .github/workflows/ci.yml
  .lintstagedrc.mjs
  apps/backoffice/.lintstagedrc.mjs
  apps/backoffice/src/env.mjs
  apps/web/.lintstagedrc.mjs
  apps/web/src/env.mjs
  packages/config-eslint/.lintstagedrc.mjs
  packages/config-lintstaged/index.mjs
  packages/config-tailwind/.lintstagedrc.mjs
  packages/config-typescript/.lintstagedrc.mjs
  packages/database/.lintstagedrc.mjs
  packages/database/package.json
  packages/logger/.lintstagedrc.mjs
  packages/mode/.lintstagedrc.mjs
  packages/mode/src/index.ts
  packages/ui/.lintstagedrc.mjs
  packages/utils/.lintstagedrc.mjs
  turbo.json
Labels: release, web, backoffice, automation

#2 deploy vercel
  .github/workflows/deploy-vercel-fn.yml
  .github/workflows/deploy-vercel.yml
Labels: release, web, automation

#3 fix prisma lint staged
  packages/config-lintstaged/index.mjs
Labels: release

#7 use vercel previews
  .github/workflows/cleanup-preview.yml
  .github/workflows/deploy-vercel-fn.yml
  .github/workflows/deploy-vercel.yml
Labels: release, automation

#8 don't post anything on github when merging.
  .github/workflows/deploy-vercel-fn.yml
  .github/workflows/deploy-vercel.yml
Labels: release, automation

#5 Font setup: tailwind configuration, fonts file, created font family
  apps/web/public/fonts/Commissioner/Commissioner-VariableFont_FLAR,VOLM,slnt,wght.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-Black.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-Bold.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-ExtraBold.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-ExtraLight.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-Light.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-Medium.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-Regular.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-SemiBold.ttf
  apps/web/public/fonts/Commissioner/static/Commissioner-Thin.ttf
  apps/web/src/app/globals.css
  apps/web/tailwind.config.ts
Labels: release, web
